### ISSUE TITLE
Can prometeus-proxy be used to proxy metrics from an external source?

### ISSUE THREAD

**Issue by joedborg** [pambrose/prometheus-proxy#102]
Here's an example.  I'm trying to use Flagger within my K8s cluster to get progressive rollouts.  It can integrate with Istio to grab metrics from it via Prometheus.  However, unless defining a bunch of custom metrics (instead of the built in ones) it seems to not be able to handle a source needing a secret access (https://github.com/fluxcd/flagger/issues/1671).

I'd like to have a proxy inside the cluster, without needing auth, that proxies to my external Prometheus, using a secret.  Thus, Flagger can just talk to the proxy, without needing the secret.

Is this possible with prometheus-proxy?

**Comment by pambrose** [comment]
Hey Joe,
I do not understand exactly what you want to do, but it sounds like something that should work. Have you tried it, and if so, what was the roadblock?
