### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by menvol3** [pambrose/prometheus-proxy#104]
Hello

I tried to start the latest version of  promethues-agent.jar (v1.22.0) on my host and received the error below

Have I missed something?
```
Error: LinkageError occurred while loading main class io.prometheus.Agent
	java.lang.UnsupportedClassVersionError: io/prometheus/Agent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

I have Java11 installed from AWS
```
openjdk 11.0.22 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-11.0.22.7.1 (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.22.7.1 (build 11.0.22+7-LTS, mixed mode)
```

**Comment by pambrose** [comment]
Can you give Java 17 a try?

**Comment by menvol3** [comment]
Yes, I can, but unfortunately, the hosts I’d like to use with Prometheus-proxy are running Java 11
Is it possible for you to build it on Java 11 as well?

**Comment by pambrose** [comment]
I will give it a try when I do the kotlin 2.1.0 release.

**Comment by pambrose** [comment]
Changing the minimum JDK from 17 to 11 seems to be working fine. Let me iron out an outstanding protobuf issue and then I will do a release.

**Comment by pambrose** [comment]
I just pushed the 1.23.0 release and it has Java 11 support. Please give it a try and let me know how it goes!

**Comment by menvol3** [comment]
It works, thank you
