### ISSUE TITLE
Duplicate charset parameter sent as response header from prompoxy to prometheus server

### ISSUE THREAD

**Issue by mhussain584** [pambrose/prometheus-proxy#105]
**Usecase:-**
I am currently implementing this solution for one of the use-case, where i am trying to pull the metrics of remote machines (parked in DC) from prometheus (cloud), i am able to pull the agent/device metrics from promproxy (cloud).
So in order scrape this endpoint and auto-discover the paths and hostnames i've enabled the env variable  _SD_ENABLED_ and set the value to promproxy hostname and port (8080)  variable _SD_TARGET_PREFIX_ .
With the above changes at promproxy level i was able to discover the hostname with the paths  on /discovery.

**Issue:-**
Now, when i try to a scrape the job with the above /discovery endpoint at the prometheus server, the server fails to parse the contentType here , as there are duplicate **charset** sent in the response header to the prom server.

`time=2024-11-27T07:20:13.087Z level=ERROR source=scrape.go:1585 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=deviceserver_metrics target=http://promproxy-us-east-1.aws-prod.xyz.com:8080/abc-test-IDS_app_metrics content_type="text/plain; charset=utf-8; charset=UTF-8" fallback_media_type="" err="cannot parse Content-Type \"text/plain; charset=utf-8; charset=UTF-8\" and no fallback_scrape_protocol for target\nmime: duplicate parameter name"`

**Workaround:-**
Added **_fallback_scrape_protocol_** as 'PrometheusText1.0.0' in the scrape config to skip the parsing check.

Please let me know if any further details are required.

**Comment by pambrose** [comment]
Hi @mhussain584 . That is interesting. I must confess to not understanding exactly what is going on with your setup. Which server do you believe is producing the invalid content-type value? Also, any idea why it is text/plain and not application/json?

**Comment by pambrose** [comment]
Also, what happens if you hit the /discovery endpoint with your browser? Do you get the same content-type value?

**Comment by mhussain584** [comment]
My setup comprises of the following:-

1. Servers (which are to be monitored) parked in DC (behind the firewall) exposes metrics on predefined ports
2. I have a mgmt machine (prom-agent) that sits in the same network listens to these servers on designated ports for the metrics
3. The next component PromProxy running in a cloud env which pulls the prom-agent metrics on port 8080, after enabling SD_ENABLED able to access the targets on their respective paths on /discovery.
4. The prometheus-server that is trying to scrape the promproxy server on endpoint :8080/discovery, is failing to parse the content type with the above exception


ANSWERS TO YOUR QUERIES

- The promproxy server is what i believe is producing the invalid content-type values, when i access the /discovery on browser i get the json of target and labels and not the text/plain , and i assume is what expected.
- The exception excerpt mentioned above is what i am getting in prometheus server logs when trying to scrape the promproxy's /discovery endpoint, and tbh i am not sure why it gives the plaintext instead of application/json.

I hope this answers the question, else please let me know if something is still not clear.

And i appreciate your response

**Comment by pambrose** [comment]
If I set up a proxy and an agent, and I enable SD_ENABLED and query the /discovery endpoint I get these headers with the response:
```
Cache-Control: must-revalidate,no-store
X-Engine: Ktor
Date: Mon, 02 Dec 2024 04:44:07 GMT
Server: Ktor/3.0.1
Content-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: application/json
```

These look completely different from what you are getting. 
Can you use Postman (or an equivalent) to query your /discovery endpoint and 
see what headers you are getting. 

For the record, based on your experience, I am assuming that I am wearing the goat horns here, 
but we need to determine the guilty code.

**Comment by mhussain584** [comment]
@pambrose  I tried using curl to call the /discovery endpoint and i get the application/json as Content-Type
`> GET /discovery HTTP/1.1
> Host: promproxy-us-east-1.aws-prod.xyz.com:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate,no-store
< X-Engine: Ktor
< Date: Mon, 02 Dec 2024 05:18:54 GMT
< Server: Ktor/3.0.1
< Content-Length: 1547
< Content-Type: application/json
<`

**Comment by mhussain584** [comment]
Sorry for the delay, @pambrose , i think the problem is not with the code that reads the /discovery but the endpoints that prometheus is scraping from /discovery.

Following is my what i get on /discovery

`[
    {
        "targets": [
            "promproxy-us-east-1.aws-prod.example.com:8080"
        ],
        "labels": {
            "__metrics_path__": "abc-xyz_ids_app_metrics",
            "agentName": "Unnamed-d16a421a3f72",
            "hostName": "promproxy-us-east-1.aws-prod.example.com",
            "cloud": "abc-xyz",
            "service": "ids",
            "ip": "10.255.10.45"
        }
    },
    {
        "targets": [
            "promproxy-us-east-1.aws-prod.example.com:8080"
        ],
        "labels": {
            "__metrics_path__": "proxy_metrics",
            "agentName": "Unnamed-d16a421a3f72",
            "hostName": "promproxy-us-east-1.aws-prod.example.com"
        }
    },
    {
        "targets": [
            "promproxy-us-east-1.aws-prod.example.com:8080"
        ],
        "labels": {
            "__metrics_path__": "abc-xyz_ids_sys_metrics",
            "agentName": "Unnamed-d16a421a3f72",
            "hostName": "promproxy-us-east-1.aws-prod.example.com",
            "cloud": "abc-xyz",
            "service": "ids",
            "ip": "10.255.10.45"
        }
    },
    {
        "targets": [
            "promproxy-us-east-1.aws-prod.example.com:8080"
        ],
        "labels": {
            "__metrics_path__": "agent_metrics",
            "agentName": "Unnamed-d16a421a3f72",
            "hostName": "promproxy-us-east-1.aws-prod.example.com",
            "cloud": "abc-xyz"
        }
    }
]`

The present scenario is, there is a machine (X) in the same network along with the device that is being monitored (10.255.10.45).

**Scenario 1:-**
Prom-agent is running on machine X, so when i access the metrics from the machine X it gives me the charset utf-8 

`curl -I http://10.255.10.45:9100/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Thu, 05 Dec 2024 06:09:56 GMT`

**Scenario 2:-**

When i access these metrics from prometheusProxy on the aforementioned targets from /discovery , that is located in cloud, i get the charset=UTF-8 in the header

`curl -I promproxy-us-east-1.aws-prod.example.com:8080/abc-xyz_ids_sys_metrics
X-Engine: Ktor
Date: Thu, 05 Dec 2024 06:07:54 GMT
Server: Ktor/3.0.1
Content-Length: 13
Content-Type: text/plain; charset=UTF-8`

**Scenario-3**
When i try and access the /discovery on 8080, i get the ContentType application/json

So, now i am trying to understand is it something at the prometheus-agent level or the prometheus-proxy level that is leading it to have redundant charset with the ContentType text/plain.

Appreciate your response

**Comment by pambrose** [comment]
Okay, that gets us closer to finding the culprit. It definitely looks like the problem is in the plumbing of the agent/proxy code. Let me work on it in the AM.

**Comment by pambrose** [comment]
I created a simple proxy/agent setup and discovered something. Your scenario 2 results are not representative of the headers you would get when doing a scrape. The -I option only issues a HEAD request, and that  is not listened for by the proxy. It only responds to GET requests. Try it again with the "-i" option, which will include the headers and the data using a GET command.

**Comment by pambrose** [comment]
You should see the parameter "version=0.0.4" in your content type when you use -i.

**Comment by pambrose** [comment]
I wanted to clarify one other thing, no scraping occurs during a call to /discovery. The /discovery endpoint just creates a JSON response based on data the agents sent when connecting. This is in reference to your comment: "the endpoints that prometheus is scraping from /discovery."

**Comment by pambrose** [comment]
Interesting!! Can you please do a "curl -i" on you scenario 1 as well.

**Comment by mhussain584** [comment]
Curl on scenario 1
`curl -i http://10.255.10.45:9100/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Mon, 09 Dec 2024 07:30:23 GMT
Transfer-Encoding: chunked`

**Comment by pambrose** [comment]
That is really bizarre. I can easily hack the content-type value to eliminate the UTF-8 value, but I really want to understand where it is coming from and fix it properly. Let me instrument the code to log the content type values all the way from the scrape to the reporting and we will be able to see where the UTF-8 value is coming from.

**Comment by pambrose** [comment]
@mhussain584 are you running the proxy and agent as jar files or docker images? I want to give you a version with more verbose logging.

**Comment by pambrose** [comment]
I pushed 1.23.1. It has additional logging for contentType info. You can enable the logging with the --debug option, setting DEBUG_ENABLED to true or setting proxy.admin.debugEnabled and agent.admin.debugEnabled to true. Please set the options on the proxy and the agent. You will see 1 "CT check" message in the agent and 4  in the proxy. Please sent me the contents of them and we should see where the problem child is.

**Comment by mhussain584** [comment]
Hi @pambrose sure let me try this

**Comment by mhussain584** [comment]
@pambrose , please let me know this is not what you are expecting
**CT check log from agent**
`06:14:39.684 INFO  [AgentHttpService.kt:136] - CT check - setScrapeDetailsAndDebugInfo() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-2]`

**CT check log from proxy**
`06:13:57.830 INFO  [ProxyHttpRoutes.kt:227] - CT check - submitScrapeRequest() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
06:13:57.859 INFO  [ProxyHttpRoutes.kt:146] - CT check - processRequests() contentTypes: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
06:13:57.860 INFO  [ProxyHttpRoutes.kt:147] - CT check - processRequests() okContentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
06:13:57.863 INFO  [ProxyHttpRoutes.kt:112] - CT check - handleClientRequests() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]`

**Comment by pambrose** [comment]
Did you use curl -i to generate these msgs? And are the two charsets still present in the ultimate output?

**Comment by mhussain584** [comment]
The above are from the container logs that are generated when i run the curl -i for both the scenarios 1 and 2

When i run (Scenario 1)
`curl -i http://10.255.10.45:9100/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Tue, 10 Dec 2024 06:52:46 GMT
Transfer-Encoding: chunked`

I get the following in the agent logs 

`06:55:09.539 INFO  [AgentHttpService.kt:136] - CT check - setScrapeDetailsAndDebugInfo() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]`


and for Scenario 2

`curl -i http://promproxy-us-east-1.aws-prod.example.com:8080/siteadmin-us-east-1-test_ids_app_metrics`

I get the following logs form the proxy container

`07:00:12.632 INFO  [ProxyHttpRoutes.kt:227] - CT check - submitScrapeRequest() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
07:00:12.633 INFO  [ProxyHttpRoutes.kt:146] - CT check - processRequests() contentTypes: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
07:00:12.633 INFO  [ProxyHttpRoutes.kt:147] - CT check - processRequests() okContentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
07:00:12.633 INFO  [ProxyHttpRoutes.kt:112] - CT check - handleClientRequests() contentType: text/plain; charset=utf-8 [DefaultDispatcher-worker-7]
07:00:12.635 INFO  [CallLogging.kt:45] - 200 OK: GET - /siteadmin-us-east-1-test_ids_app_metrics - ip-100-65-70-119.ec2.internal [DefaultDispatcher-worker-1]`

**Comment by pambrose** [comment]
So the utf-8 charset is present, but the UTF-8 charset is not present? That looks like it is working as expected. So, when were you getting the UTF-8 charset values?

**Comment by pambrose** [comment]
Sorry, I just saw your comment that you are no longer getting the UTF-8 values. Hmmm. I am happy to hear that, but I wish I could claim it was something that I did. Is you original deserialization issue now working?

**Comment by mhussain584** [comment]
When i run curl -i from the promproxy on version 1.23.0 i still get 2 charsets

`curl -i http://promproxy-us-east-1.aws-prod.example.com:8080/siteadmin-us-east-1-test_ids_app_metrics
HTTP/1.1 200 OK
Cache-Control: must-revalidate,no-store
Cache-Control: must-revalidate,no-store
X-Engine: Ktor
Date: Tue, 10 Dec 2024 07:17:25 GMT
Server: Ktor/3.0.1
Content-Length: 4909
Content-Type: text/plain; charset=utf-8; charset=UTF-8
`
But with the 1.23.1 it doesn't , so something changed with the latest version
`curl -i http://promproxy-us-east-1.aws-prod.example.com:8080/siteadmin-us-east-1-test_ids_app_metrics
HTTP/1.1 200 OK
Cache-Control: must-revalidate,no-store
Cache-Control: must-revalidate,no-store
X-Engine: Ktor
Date: Tue, 10 Dec 2024 07:05:51 GMT
Server: Ktor/3.0.2
Content-Length: 4909
Content-Type: text/plain; charset=utf-8`

**Comment by mhussain584** [comment]
Whatever changed with 1.23.1 has fixed the duplicate charset issue, my deserialisation is now working as expected, Thanks a ton @pambrose appreciate.

**Comment by pambrose** [comment]
Excellent! I will take the win. Thanks for working through the issue!
