### ISSUE TITLE
To many open files 

### ISSUE THREAD

**Issue by darox** [pambrose/prometheus-proxy#49]
I am facing the issue that prometheus-proxy stops working after a few hours due to "to many open files". After increasing the amount of file descriptors it runs for a longer time but still stops working after a few hours. Is this a known issue?

Thank you

**Comment by pambrose** [comment]
Hi Dario,

That is not cool. I have not seen that before. The proxy is ultimately just a gRPC server, so my first guess would be that it is a gRPC issue. I can see reports of other gRPC servers having similar issues when I search the web. Let me look at it in the AM.

Paul

**Comment by pambrose** [comment]
What version of the proxy are you using?

**Comment by darox** [comment]
I have switched to nginx because I haven't time to further investigate.
