### ISSUE TITLE
how many apps does one prometheus-agent support?

### ISSUE THREAD

**Issue by shaotingEri** [pambrose/prometheus-proxy#57]
hi,
I'm using your product.
And I have almost 200 apps. eg. app1_metrics app2_metrics ……app189_metrics
I find some data is missed.
curl http://mymachine.local:8080/app1_metrics    --> OK
curl http://mymachine.local:8080/app30_metrics    --> OK
curl http://mymachine.local:8080/app123_metrics    --> 404 Not Found

Of course, the number is just an example, don't know the exact number.
So, I want to ask you:
Do you know how many apps for one prometheus-agent support?

**Comment by pambrose** [comment]
Hi,

The scaling is dependent on the resources you are using. The proxy and agent are built on top of gRPC, which is well-tested infrastructure. 

I would expect an agent to be able to handle 200 clients. Are you seeing success with a smaller number of clients? Do you see errors when more clients are added?

Paul

**Comment by shaotingEri** [comment]
thank you for your idea.
seems it's the network issue.😄
