### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by kitich** [pambrose/prometheus-proxy#61]
Is it possible to use agent when local_apps have metrics with basic auth? 

There is no config options for username:password, and http://user:pass@address/metrics doesn't work.

**Comment by pambrose** [comment]
Yeah, good question. That sounds like a reasonable thing to expect. Let me look into it.

**Comment by pambrose** [comment]
I posted 1.9.1, which has support for basic auth. Include the username/password in the URL as you suggested above. Please let me know how it works for you.

**Comment by kitich** [comment]
Yes, it's working. Thank!

**Comment by pambrose** [comment]
Glad to hear it!
