### ISSUE TITLE
Is it possible to publish this for use in Spring Boot projects?

### ISSUE THREAD

**Issue by joshblease** [pambrose/prometheus-proxy#63]
Hi Paul,

I'd love to use the agent embedded within a spring boot application of mine, however the "javax.servlet" is causing me some headaches and I can't exclude the dependency to use the version that comes with spring. Is there anyway you could publish the project for use in other applications at all?

**Comment by joshblease** [comment]
Resolved this with jitpack and a bit of trial & error with gradle imports, eventually settled on this which seem to work for me:
```implementation "org.jetbrains.kotlin:kotlin-stdlib:1.5.0"
    implementation "com.google.guava:guava:30.1.1-jre"
    implementation "com.github.pambrose.common-utils:guava-utils:1.10.0"
    implementation "com.github.pambrose.common-utils:service-utils:1.10.0"
    implementation 'com.github.pambrose:prometheus-proxy:1.9.1'

**Comment by pambrose-ef** [comment]
Hi Josh,

Are you embedding the agent on your app or are you running it as a standalone process? 

That javax.servlet package is getting dragged in by Jetty, which is used for reporting metrics by Dropwizard. 

Paul

**Comment by joshblease** [comment]
I've embedded it within the application as it was a requirement to only have one executable for our use case. It works well within it after overcoming the few dependency issues and using Java+Kotlin.

**Comment by pambrose** [comment]
Glad to hear embedding it worked well for you. That approach is less hassle than using an agent.
