### ISSUE TITLE
Eclipse Jetty DoS Vulnerability (GHSA-8mpp-f3f7-xc28)

### ISSUE THREAD

**Issue by gsi-eduardopuig** [pambrose/prometheus-proxy#86]
Jetty's version presents a DoS Vulnerability as can be seen [here](https://github.com/advisories/GHSA-8mpp-f3f7-xc28).
I use docker version of prometheus-proxy v.1.14.2 and it uses Jetty:// 9.4.49.v20220914. 
Recommendations to fix this problem, update to 10.0.10 or 11.0.10, which are patched versions.
Hope this helps!

**Comment by pambrose** [comment]
Thanks @gsi-eduardopuig!

I updated the jetty jar to 10.0.13 and released version 1.15.0 of prometheus_proxy with the changes.
