### ISSUE TITLE
Explanation of Service Discovery

### ISSUE THREAD

**Issue by sane4ek-2** [pambrose/prometheus-proxy#91]
Could you explain me what exactly SD exposes? Does it expose services behind the agents or maybe exposes agents or something else?

Thank you.

**Comment by pambrose** [comment]
The proxy SD options expose the Prometheus SD functionality described here: https://prometheus.io/docs/prometheus/latest/http_sd/

**Comment by sane4ek-2** [comment]
Ohh, I know what will help - an example of usage SD in the context of prometheus proxy.

**Comment by sane4ek-2** [comment]
Perhaps, I got the idea. SD in the proxy allows us not to edit `prometheus.yml` config in a section `static_configs` when new agents connect to the proxy. But before it becomes working I have to define a job with `http_sd_configs` in `prometheus.yml`

**Comment by pambrose** [comment]
The SD endpoint reports the meta info for the targets that have been defined for the proxy to scrape.

**Comment by pambrose** [comment]
I have never needed to use the service discovery endpoint, but users asked me to add it so I did.
