### ISSUE TITLE
Prometheus proxy uses a lot of memory

### ISSUE THREAD

**Issue by danvatca** [pambrose/prometheus-proxy#97]
I am running a lot of deployments with the same architecture, with a prometheus that scrapes remote systems through a prometheus proxy.
The things that is strange is the amount of memory that prometheus proxy uses. Here's an example:
```
prometheus-k8s-0                      15m          693Mi
prometheus-proxy-69945d644-w4wzm      17m          2995Mi
```
Why would the proxy use much more memory than even prometheus?
Could this be a memory leak?

**Comment by pambrose** [comment]
Hi Dan,
Does the amount of memory continue to grow over time, or does it level off?  If it levels off, then I think you are observing the relative memory footprint of a Go app vs a JVM-based app. I have not had any reports of memory leaks, and there are thousands of people using the proxy. That said, if the memory usage is not leveling off, I will look into it and see what might be happening.
Cheers,
Paul
